Nagios host env
salt-formulas/salt-formula-heka pull request #106
Opened 2016-12-12 14:58 UTC by SwannCroiset

Suffix Nagios host with the environment_label dimension

2016-12-12 15:39 UTC, simonpasquier requested changes

2016-12-12 15:39 UTC, simonpasquier commented on heka/files/lua/encoders/status_nagios.lua
> +    if host_suffix_dimension_key then
(nit) I would read `Fields[<host_suffix_dimension_key>]` first and only append if it's not nil.

2016-12-12 15:39 UTC, simonpasquier commented on heka/files/lua/encoders/status_nagios.lua
> +    if host_suffix_dimension_key then
```
if host_suffix_dimension_field then
  local suffix = read_message(host_suffix_dimension_field)
  if suffix then
    host = host .. '.' .. suffix
  end
end
data['host'] = host
```

2016-12-12 15:39 UTC, simonpasquier commented on heka/files/lua/encoders/status_nagios.lua
> +local host_suffix_dimension_key = read_config('host_suffix_dimension_key')
nit but you could build `Fields[...]` just once here:

```
local host_suffix_dimension_field
if read_config('host_suffix_dimension_key') then
  host_suffix_dimension_field = string.format('Fields[%s]', read_config('host_suffix_dimension_key'))
end
```

2016-12-13 08:31 UTC, SwannCroiset commented on heka/files/lua/encoders/status_nagios.lua
> +local host_suffix_dimension_key = read_config('host_suffix_dimension_key')
done

2016-12-13 08:31 UTC, SwannCroiset commented on heka/files/lua/encoders/status_nagios.lua
> +    if host_suffix_dimension_key then
done

2016-12-13 13:03 UTC, elemoine approved these changes
With "nit" comments.

2016-12-13 13:03 UTC, elemoine commented on heka/files/lua/encoders/status_nagios.lua
> +end
(nit) You could avoid reading the config twice. Up to you.

```lua
local host_suffix_dimension_field
local host_suffix_dimension_key = read_config('host_suffix_dimension_key')
if host_suffix_dimension_key then
     host_suffix_dimension_field = string.format('Fields[%s]', host_suffix_dimension_key)
end
```

2016-12-13 13:03 UTC, elemoine commented on heka/files/lua/encoders/status_nagios.lua
> +end
Ditto.

2016-12-13 15:51 UTC, simonpasquier approved these changes

2016-12-13 16:20 UTC, merged