Final rework of status_of_members policy
salt-formulas/salt-formula-heka pull request #107
Opened 2016-12-12 16:34 UTC by ppetit

Hopefuly...

2016-12-12 16:35 UTC, elemoine requested changes

2016-12-12 16:35 UTC, elemoine commented on heka/meta/heka.yml
> +       trigger:
indent

2016-12-12 17:04 UTC, ppetit commented on heka/meta/heka.yml
> +       trigger:
arrghh....

2016-12-13 08:05 UTC, simonpasquier approved these changes

2016-12-13 08:05 UTC, merged