Adding support for sensu as alerting destination
salt-formulas/salt-formula-heka pull request #114
Opened 2017-01-19 16:20 UTC by ppetit

The AFD and GSE metrics are sent by the aggregator to local sensu-client.
A sensu-client client should be running on all nodes though (not only the
aggregator) for the sensu integrtion to work correctly.

2017-01-23 08:49 UTC, simonpasquier approved these changes

2017-01-23 08:51 UTC, simonpasquier commented
It requires https://github.com/tcpcloud/salt-formula-heka/pull/116 before merging.

2017-01-23 09:05 UTC, gthvn1 approved these changes

2017-01-23 10:02 UTC, SwannCroiset approved these changes

2017-01-23 10:28 UTC, cznewt commented
Hello, I'd like to have the meta setup correctly, I mean service metadata
// service.metadata.aggregator/output/nagios.yml
heka:
  aggregator:
    output:
      nagios_dash:
        engine: nagios
        host:
        port:
        ...
// service.metadata.aggregator/output/sensu.yml
      sensu_dash:
        engine: sensu
        host:
        port:
        ...
// service.metadata.aggregator/output/influxdb.yml
      sensu_dash:
        engine: sensu
        host:

Having this way provides required flexibility to setup 1 or more of these.

2017-02-01 13:14 UTC, simonpasquier requested changes

2017-02-01 13:14 UTC, simonpasquier commented on heka/meta/heka.yml
> +        host_suffix_dimension_key: environment_label
it can be removed since it doesn't seem to be used by the encoder

2017-02-03 13:57 UTC, thouveng commented
I tested it and it seems that there is an structure that is not closed correctly. I have the following issue:

```
mon01.mk22-lab-dvr.local:
    Data failed to compile:
----------
    Rendering SLS 'base:heka.log_collector' failed: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
/var/cache/salt/minion/files/base/heka/meta/heka.yml(602):
---
[...]
      engine: elasticsearch
      server: "http://{{ ceilometer_collector.elasticsearch_host }}:{{ ceilometer_collector.elasticsearch_port }}"
      message_matcher: "Type == 'ceilometer_resources'"
      encoder: elasticsearch_resource_encoder
  {%- endif %}
{%- endif %}    <======================
---
----------
    Rendering SLS 'base:heka.metric_collector' failed: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
/var/cache/salt/minion/files/base/heka/meta/heka.yml(602):
---
[...]
      engine: elasticsearch
      server: "http://{{ ceilometer_collector.elasticsearch_host }}:{{ ceilometer_collector.elasticsearch_port }}"
      message_matcher: "Type == 'ceilometer_resources'"
      encoder: elasticsearch_resource_encoder
  {%- endif %}
{%- endif %}    <======================
---
----------
    Rendering SLS 'base:heka.remote_collector' failed: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
/var/cache/salt/minion/files/base/heka/meta/heka.yml(602):
---
[...]
      engine: elasticsearch
      server: "http://{{ ceilometer_collector.elasticsearch_host }}:{{ ceilometer_collector.elasticsearch_port }}"
      message_matcher: "Type == 'ceilometer_resources'"
      encoder: elasticsearch_resource_encoder
  {%- endif %}
{%- endif %}    <======================
---
----------
    Rendering SLS 'base:heka.aggregator' failed: Jinja syntax error: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
/var/cache/salt/minion/files/base/heka/meta/heka.yml(602):
---
[...]
      engine: elasticsearch
      server: "http://{{ ceilometer_collector.elasticsearch_host }}:{{ ceilometer_collector.elasticsearch_port }}"
      message_matcher: "Type == 'ceilometer_resources'"
      encoder: elasticsearch_resource_encoder
  {%- endif %}
{%- endif %}    <======================

```

2017-02-03 14:03 UTC, gthvn1 requested changes
~~There is no corresponding endif~~ done in the code

2017-02-03 14:46 UTC, ppetit commented on heka/meta/heka.yml
> +        host_suffix_dimension_key: environment_label
Correct. Will remove.

2017-02-03 14:47 UTC, gthvn1 requested changes
~~UDP output required "host" and "port"~~ done in the code

2017-02-03 14:52 UTC, gthvn1 requested changes

2017-02-03 14:52 UTC, thouveng commented on heka/meta/heka.yml
> +  {%- if aggregator.sensu_host is defined %}
corresponding "endif" is missing

2017-02-03 14:52 UTC, thouveng commented on heka/meta/heka.yml
> +      address: "{{ aggregator.sensu_host }}:{{aggregator.sensu_port }}"
UDP output requires "host" and "port" not "address"

2017-02-03 17:36 UTC, ppetit commented on heka/meta/heka.yml
> +  {%- if aggregator.sensu_host is defined %}
This is fixed in new commit.

2017-02-06 10:51 UTC, gthvn1 approved these changes
Tested on my env and LGTM.

2017-02-06 12:52 UTC, merged