New model
salt-formulas/salt-formula-heka pull request #12
Opened 2016-10-25 09:12 UTC by cznewt

2016-10-25 09:25 UTC, SwannCroiset requested changes

2016-10-25 09:25 UTC, SwannCroiset commented on README.rst
> +            notifications: False
notifications and alerting properties are currently expressed by only one property:

alerting: disabled|enabled|enabled_with_notification

2016-10-25 09:35 UTC, elemoine commented on README.rst
> +            notifications: False
I did not want to bring this up right now, but, just like Swan, I am interested to understand why you changed this @cznewt.

2016-11-08 15:12 UTC, elemoine commented
This can be closed. The model defined in this PR is actually being implemented in the stacklight branch.

2016-11-08 15:12 UTC, closed without merging