Add monitoring of the Heka processes
salt-formulas/salt-formula-heka pull request #34
Opened 2016-11-08 15:46 UTC by simonpasquier

2016-11-08 19:12 UTC, elemoine requested changes

2016-11-08 19:12 UTC, elemoine commented on heka/meta/collectd.yml
> +        match: 'heka.*aggregator_collector'
The aggregator is named `aggregator`, not `aggregator_collector`.

2016-11-09 09:52 UTC, simonpasquier commented on heka/meta/collectd.yml
> +        match: 'heka.*aggregator_collector'
Good catch!

2016-11-09 09:57 UTC, elemoine approved these changes

2016-11-09 10:02 UTC, merged