[WIP] Enable collection of notifications
salt-formulas/salt-formula-heka pull request #40
Opened 2016-11-10 10:18 UTC by simonpasquier

2016-11-14 09:14 UTC, SwannCroiset requested changes

2016-11-14 09:14 UTC, SwannCroiset commented on heka/meta/heka.yml
> +  encoder:
duplicate "encoder" key L198

2016-11-14 09:21 UTC, simonpasquier commented on heka/meta/heka.yml
> +  encoder:
done

2016-11-16 09:35 UTC, simonpasquier commented
@SwannCroiset can you review this again?

2016-11-16 09:53 UTC, elemoine approved these changes

2016-11-16 09:58 UTC, elemoine commented on heka/meta/heka.yml
> +{%- for notification_level in ['info', 'warn', 'error'] %}
Maybe a bit personal, but I'd use a tuple rather than a list here.

2016-11-16 15:59 UTC, simonpasquier commented on heka/meta/heka.yml
> +{%- for notification_level in ['info', 'warn', 'error'] %}
done

2016-11-17 10:47 UTC, SwannCroiset approved these changes

2016-11-17 11:29 UTC, merged