Redefine alerting propety
salt-formulas/salt-formula-heka pull request #45
Opened 2016-11-10 15:00 UTC by SwannCroiset

The alerting property can be one of 'disabled', 'enabled' or
'enabled_with_notification'

2016-11-10 15:08 UTC, elemoine commented on heka/files/toml/filter/afd_alarm.toml
> +{%- if alerting != 'disabled' and alerting != False %}
s/!=/is not/ ?

2016-11-10 15:08 UTC, elemoine commented on heka/files/toml/filter/afd_alarm.toml
> +{% endif %}
dash missing

2016-11-10 15:09 UTC, elemoine commented
Shouldn't the same be done in the gse_alarm_cluster.toml file? https://github.com/tcpcloud/salt-formula-heka/blob/stacklight/heka/files/toml/filter/gse_alarm_cluster.toml

2016-11-10 15:11 UTC, elemoine commented
Also, I don't think the Lua code handles `enable_notification` right now.

2016-11-10 15:17 UTC, SwannCroiset commented
> s/!=/is not/

```
 Comment: Unable to manage file: Jinja syntax error: expected token 'name', got 'string'; line 17
          ---
          [...]
          hostname = "{{ grains.host }}"
          dimensions = '{{ salt['heka_alarming.dimensions'](alarm)|json }}'
          {%- set alerting = alarm.get('alerting', 'enabled') %}      
          {%- if alerting is not 'disabled' and alerting is not False %}    <======================
```

2016-11-10 15:17 UTC, SwannCroiset commented
> Shouldn't the same be done in the gse_alarm_cluster.toml file? https://github.com/tcpcloud/salt-formula-heka/blob/stacklight/heka/files/toml/filter/gse_alarm_cluster.toml

yep

2016-11-10 15:19 UTC, SwannCroiset commented
> Also, I don't think the Lua code handles enable_notification right now.
you are right .. it should be handled for smtp notification (email sent by heka)

2016-11-10 16:02 UTC, simonpasquier requested changes

2016-11-10 16:02 UTC, simonpasquier commented on heka/files/toml/filter/afd_alarm.toml
> +{%- set alerting = alarm.get('alerting', 'enabled') %}
would be better to do it in _modules/heka_alarming.py

2016-11-14 09:10 UTC, SwannCroiset commented on heka/files/toml/filter/afd_alarm.toml
> +{%- set alerting = alarm.get('alerting', 'enabled') %}
> would be better to do it in _modules/heka_alarming.py

done

2016-11-14 09:18 UTC, elemoine requested changes

2016-11-14 09:18 UTC, elemoine commented on heka/files/toml/filter/afd_alarm.toml
> +enable_notification = {{ salt['heka_alarming.alarm_enable_notification'](alarm.get('alerting', 'disabled')) }}
I'd rewrite this as follows:

```
{%- set alerting = alarm.get('alerting', 'enabled') %}
activate_alerting = {{ salt['heka_alarming.alarm_activate_alerting'](alerting) }}
enable_notification = {{ salt['heka_alarming.alarm_enable_notification'](alerting) }}
```

2016-11-14 09:18 UTC, elemoine commented on heka/files/toml/filter/gse_alarm_cluster.toml
> +enable_notification = {{ salt['heka_alarming.alarm_enable_notification'](alarm_cluster.get('alerting', 'enabled_with_notification')) }}
Ditto.

2016-11-14 09:34 UTC, SwannCroiset commented on heka/files/toml/filter/afd_alarm.toml
> +enable_notification = {{ salt['heka_alarming.alarm_enable_notification'](alarm.get('alerting', 'disabled')) }}
@elemoine done

2016-11-14 09:34 UTC, elemoine approved these changes

2016-11-14 09:48 UTC, SwannCroiset commented on heka/files/toml/filter/afd_alarm.toml
> +{%- set alerting = alarm.get('alerting', 'enabled') %}
@simonpasquier done

2016-11-15 15:32 UTC, merged