Add an os_telemetry_collector service
salt-formulas/salt-formula-heka pull request #58
Opened 2016-11-18 10:21 UTC by ityaptin

Service os_telemetry_collector implements receiving Сeilometer samples
from RabbitMQ and pulling them to InfluxDB (samples) and
ElasticSearch (resources).

2016-11-18 10:21 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2016-11-18 10:50 UTC, elemoine requested changes
It looks good @ityaptin!

2016-11-18 10:50 UTC, elemoine commented on heka/_service.sls
> +    'alarm_cluster': {},
You can remove `trigger` and `alarm_cluster`, as no alarms will be configured in the telemetry collector.

2016-11-18 10:50 UTC, elemoine commented on heka/files/heka.service
> +    chown -R heka:heka /var/cache/{{ service_name }}
Why did you add this? Have you found an actual problem? If so I think a separate PR should be created.

2016-11-18 10:50 UTC, elemoine commented on heka/files/lua/common/extra_fields.lua
> +return M
Remove this file. We already have an `extra_fields.lua`. It's in `heka/files` and its content is generated based on some variable in the model.

2016-11-18 10:50 UTC, elemoine commented on heka/map.jinja
> +    'elasticsearch_port': default_elasticsearch_port,
What about rabbit?

2016-11-18 10:50 UTC, elemoine commented on heka/meta/heka.yml
> +      message_matcher: "Fields[aggregator] == NIL && Type =~ /ceilometer_samples$/"
Remove `Fields[aggregator] == NIL`. It was removed for the other services.

2016-11-18 11:01 UTC, SwannCroiset requested changes

2016-11-18 11:01 UTC, SwannCroiset commented on heka/os_telemetry_collector.sls
> +
you need to add this : 
```
{%- from "heka/map.jinja" import os_telemetry_collector with context %}
{%- set server = os_telemetry_collector %}
```
https://github.com/tcpcloud/salt-formula-heka/blob/stacklight/heka/metric_collector.sls#L6-L7

2016-11-18 11:01 UTC, SwannCroiset commented on heka/meta/heka.yml
> +  encoder:
you'll get a wrong syntax influxdb_host is not defined but ES is defined:
```encoder:```  key will be missing

2016-11-18 11:01 UTC, SwannCroiset commented on heka/files/heka.service
> +    chown -R heka:heka /var/cache/{{ service_name }}
agree

2016-11-18 12:28 UTC, ityaptin commented on heka/_service.sls
> +    'alarm_cluster': {},
Ok, will do

2016-11-18 12:28 UTC, ityaptin commented on heka/files/heka.service
> +    chown -R heka:heka /var/cache/{{ service_name }}
Ok, will remove from this PR

2016-11-18 12:29 UTC, ityaptin commented on heka/files/lua/common/extra_fields.lua
> +return M
I will remove it

2016-11-18 12:52 UTC, ityaptin commented on heka/map.jinja
> +    'elasticsearch_port': default_elasticsearch_port,
I've added a rabbit defaults here

2016-11-18 12:53 UTC, ityaptin commented on heka/os_telemetry_collector.sls
> +
fixed

2016-11-18 12:53 UTC, ityaptin reviewed
@elemoine @SwannCroiset I fixed your comments

2016-11-21 13:39 UTC, cznewt commented
I have one bigger thought, I'd rather have remote_collector implemented on ceilometer service metadata populating the remote_collector with inputs/decoder/filter definitions instead of separate heka service for os/ceilometer telemetry.

2016-11-21 13:58 UTC, simonpasquier requested changes

2016-11-21 13:58 UTC, simonpasquier commented on heka/map.jinja
> +    'rabbit_vhost': default_rabbit_queue,
typo: 'rabbitmq_vhost'

2016-11-21 13:58 UTC, simonpasquier commented on heka/meta/heka.yml
> +        time_precision: "ns"
ideally it shouldn't be hardcoded

2016-11-21 14:25 UTC, ityaptin commented on heka/map.jinja
> +    'rabbit_vhost': default_rabbit_queue,
I'll fix it

2016-11-21 14:26 UTC, ityaptin commented on heka/meta/heka.yml
> +        time_precision: "ns"
Simon, I think there is no problem to move time_precision to variable. I will check and change it.

2016-11-21 15:13 UTC, ityaptin commented
@cznewt: Hi! We implemented os_telemetry_collector as a separate service because in my mind new service should have availability to have own configs and been installed on different nodes. Own configs are especially important in deployments with a detached rabbitmq server for monitoring data from ceilometer (it's in a plan how I know). Also managing of this service separately could be useful for end users of ceilometer. 
Next important point is a time. I think it's better to keep this stuff in os_telemetry_collector in this time slot, because we tested it a little during development, but we could think about moving code to remote_collector in the future.

2016-11-22 08:16 UTC, elemoine commented
> I have one bigger thought, I'd rather have remote_collector implemented on ceilometer service metadata populating the remote_collector with inputs/decoder/filter definitions instead of separate heka service for os/ceilometer telemetry.

Why? What is the problem with having a separate service for Telemetry? Having a separate service is more flexible, for example allowing the remote_collector and telemetry_collector to run on separate servers (as already mentioned by @ityaptin). So for now, I'd go with a separate instance. We can revisit this later if it causes problem.

2016-11-24 12:03 UTC, simonpasquier requested changes

2016-11-24 12:03 UTC, simonpasquier commented on heka/init.sls
> +{%- if pillar.heka.os_telemetry_collector is defined %}
please move it before `- heka.aggregator`. This is because of grains file's generation.

2016-11-24 12:03 UTC, simonpasquier commented on heka/meta/heka.yml
> +      {%- if os_telemetry_collector.resource_decoding is defined %}
the `resource_decoding` parameter can be added to map.jinja and then:
```
  decode_resources: {{ os_telemetry_collector.resource_decoding|lower }}
```

2016-11-24 12:14 UTC, ityaptin commented on heka/init.sls
> +{%- if pillar.heka.os_telemetry_collector is defined %}
I will do

2016-11-25 14:23 UTC, cznewt approved these changes
LGTM, the separate role for ceilometer service makes sense

2016-11-25 14:26 UTC, simonpasquier approved these changes

2016-11-25 14:27 UTC, SwannCroiset approved these changes

2016-11-25 14:48 UTC, cznewt approved these changes

2016-11-25 14:48 UTC, cznewt commented on heka/_service.sls
> +    'decoder': {},
here probably to ceilometer_collector as well

2016-11-25 14:49 UTC, merged