Added a policy for members of node clusters
salt-formulas/salt-formula-heka pull request #84
Opened 2016-12-02 11:05 UTC by ppetit

Added new policy for cluster of nodes.

2016-12-02 13:35 UTC, simonpasquier approved these changes

2016-12-06 09:05 UTC, elemoine requested changes

2016-12-06 09:05 UTC, elemoine commented on heka/meta/heka.yml
> +  # A policy that is typically used for storage or compute clusters
Indent

2016-12-06 09:24 UTC, elemoine requested changes

2016-12-06 09:24 UTC, elemoine commented on heka/meta/heka.yml
> +          function: percent
Note: if more than 50% of members are down or critical then it is not possible to also have more than 50% of members in the okay state, so I think the second rule is not necessary.

2016-12-06 12:14 UTC, ppetit commented on heka/meta/heka.yml
> +          function: percent
yes that makes sense. I'll fix it.

2016-12-06 12:46 UTC, elemoine approved these changes

2016-12-06 12:46 UTC, merged