[WIP] Add missing default values
salt-formulas/salt-formula-heka pull request #91
Opened 2016-12-06 13:37 UTC by elemoine

2016-12-06 14:08 UTC, elemoine commented
This is ready for review.

2016-12-07 09:50 UTC, ityaptin approved these changes

2016-12-07 09:53 UTC, simonpasquier approved these changes

2016-12-07 09:58 UTC, cznewt requested changes

2016-12-07 09:58 UTC, cznewt commented on heka/map.jinja
> +    'amqp_port': default_amqp_port,
Well, I disapprove. this is not the way the things should be structured, output backends cannot be mixed to one list like this. I need the separated approach to sustain flexibility. I can help with this/explain to details.

2016-12-07 11:53 UTC, cznewt approved these changes

2016-12-07 11:54 UTC, cznewt commented
We'll deal with separate backends later.

2016-12-07 11:54 UTC, merged